### PR TITLE
Fix job pod status display

### LINKED ISSUE #2459: Job pod status is not updated on failed / succeed
##### Environment
KOPS 1.7.8 - AWS
```
Dashboard version: 1.7.0 and 1.7.1
Kubernetes version: 1.7.8
Operating system: Debian 8
Node.js version: N/A
Go version: N/A
```

##### Steps to reproduce
Run a Job to completion using the settings:
```yaml
Parallelism:              1
Completions:              1
Active Deadline Seconds:  1200s
```
##### Observed result
Job runs until pod failed / succeeded,  status stays the same:
`Status 
  Pods: 0 active  0 succeeded  0 failed`

##### Expected result
When using `kubectl describe job some-job` you can clearly see that the job status is completed / failed
`Pods Statuses:            0 Running / 1 Succeeded / 0 Failed`

### PR DESCRIPTION
**Pull request by floreks**
Fixes #2459. I am only overriding it since there are some additional info in `PodInfo` structures tha I don't want to loose.

This is the code fragment in `kubectl` that displays this information: https://github.com/kubernetes/kubernetes/blob/ededef24e4b7425784b97cd5d661399592c06ffe/pkg/printers/internalversion/describe.go#L1690

### CODE REVIEW

File: src/app/backend/resource/job/detail.go [hunk 1]
```diff
@@ -91,6 +91,11 @@ func GetJobDetail(client k8sClient.Interface, metricClient metricapi.MetricClien
 
 func toJobDetail(job *batch.Job, eventList common.EventList, podList pod.PodList, podInfo common.PodInfo,
 	nonCriticalErrors []error) JobDetail {
+	// This pod info for jobs should be get from job status, similar to kubectl describe logic.
+	podInfo.Running = job.Status.Active
+	podInfo.Succeeded = job.Status.Succeeded
+	podInfo.Failed = job.Status.Failed
```
Comment (maciaszczykm) [inline src/app/backend/resource/job/detail.go]: It should be changed in `getJobPodInfo()` method from `resource/job/pods.go` file.

**Comment by innovia** [comment]
Wow that was fast thanks alot!!!

When will it be released? Should i build from master?

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/Installation#development-release

**Comment by maciaszczykm** [comment]
@innovia It will be available on development image until official release. Wait until build finishes.

**Comment by maciaszczykm** [comment]
https://travis-ci.org/kubernetes/dashboard/builds/286474353
