### PR TITLE
App name validation fix

### LINKED ISSUE #411: Services are up to 24 chars long. Make app name at least that long.
This is what happened when I wanted to create a service with more that 24 chars: 

```
 Details: must be a DNS 952 label (at most 24 characters, matching regex [a-z]([-a-z0-9]*[a-z0-9])?): e.g. "my-name"
```

### PR DESCRIPTION
**Pull request by digitalfishpond**
#411 
App name is restricted to 24 chars and regex pattern now also restricts first char to lowercase letter

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/451)

### CODE REVIEW

File: src/app/frontend/deploy/deployfromsettings_controller.js [hunk 1]
```diff
@@ -127,13 +127,13 @@ export default class DeployFromSettingsController {
...
      */
-    this.namePattern = new RegExp('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$');
+    this.namePattern = new RegExp('^[a-z]([-a-z0-9]*[a-z0-9])?$');
 
     /**
      * Maximum length for Application name
      * @export {string}
      */
-    this.nameMaxLength = '63';
+    this.nameMaxLength = '24';
```
Comment (cheld) [inline src/app/frontend/deploy/deployfromsettings_controller.js]: test must be adapted as well

Comment (digitalfishpond) [inline src/app/frontend/deploy/deployfromsettings_controller.js]: @cheld PTAL

**Comment by cheld** [comment]
LGTM

**Comment by bryk** [comment]
:lgtm: 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/451#-:-KBhDXbdDignLTFtADF6:980077423)*
