### PR TITLE
Hide basicAuth and opaque secret data

### LINKED ISSUE #1291: Dashboard v1.4.0 incorrectly renders opaque secrets
#### Issue details

the new dashboard shows any secret including opaque ones I would have expected this to have the same behaviour as kubectl which will only list the file names of an opaque secret not the contents
##### Environment

```
Dashboard version: v1.4.0
Kubernetes version: v1.4.0
Operating system: coreos
Node.js version: n/a
Go version: n/a
```
##### Steps to reproduce

deploy the currently manifest for v1.4.0 dashboard and add an opaque secret to your kubernetes cluster then try to view it in the ui
##### Observed result

I can see the full details of any secret via the web ui dashboard even opaque ones
##### Expected result

I would expect to see a listing on the secrets but no contents similar to what kubectl shows.

### PR DESCRIPTION
**Pull request by batikanu**
This fixes #1291

### CODE REVIEW

File: src/app/backend/resource/secret/secretdetail.go [hunk 1]
```diff
@@ -20,6 +20,8 @@ import (
 	"github.com/kubernetes/dashboard/src/app/backend/resource/common"
 	"k8s.io/kubernetes/pkg/api"
 	client "k8s.io/kubernetes/pkg/client/unversioned"
+	//"fmt"
```
Comment (maciaszczykm) [inline src/app/backend/resource/secret/secretdetail.go]: Not needed.

Comment (batikanu) [inline src/app/backend/resource/secret/secretdetail.go]: Thanks. PTAL

File: src/app/backend/resource/secret/secretdetail.go [hunk 2]
```diff
@@ -51,11 +52,24 @@ func GetSecretDetail(client *client.Client, namespace, name string) (*SecretDeta
 	return getSecretDetail(rawSecret), nil
 }
 
+func hideSecretData(rawSecret *api.Secret) map[string][]byte {
+	// For opaque and basicAuth secret types the credentials like username, password and etc. should be hidden.
+	if rawSecret.Type == api.SecretTypeOpaque || rawSecret.Type == api.SecretTypeBasicAuth {
+		data := make(map[string][]byte)
+		for key, value := range rawSecret.Data {
+			data[key] = []byte(fmt.Sprintf("%d bytes", len(value)))
```
Comment (bryk) [inline src/app/backend/resource/secret/secretdetail.go]: Hmm... This is not translatable. Can you send the data and render it on the client as the `FOO bytes`? 

And can you make sure to enable the option of rendering this fully? I.e., `foo-secret: 1234 bytes (show value)`. This is because we cannot entirely hide the value of the secret. Hiding it by default is nice, but entirely, not that much. 

@maciaszczykm @digitalfishpond What do you think?

Comment (maciaszczykm) [inline src/app/backend/resource/secret/secretdetail.go]: I agree, the best option seems to be adding switch like `(show value)` and hiding value by default.

Comment (ashmere) [inline src/app/backend/resource/secret/secretdetail.go]: @bryk @maciaszczykm  personally unless it is a startup flag for the dashboard I don't think there should be an option on a production kubernetes dashboard to see opaque secret, as this can expose a lot of things the general kubernetes admin/user thought was secure to anyone with access to the UI.

Comment (bryk) [inline src/app/backend/resource/secret/secretdetail.go]: But such thing would be only an illusion of security. CLI and API returns opaque secrets with full info to all users. So if a user can see the secret, they can see its opaque content.

**Comment by batikanu** [comment]
How about this?

hiddentext

**Comment by bryk** [comment]
@batikanu Oh, yeah, this looks cool! 

I'm wondering whether this should be links or toggles. We have links "show more" +then "show less" when there are more than X labels on a resource. It feels more natural to me, because here it is unclear what happens when you toggle the toggle. Will it "show more" or is currently "showing more"? 
@romlein @rf232  Can you comment on this?

**Comment by maciaszczykm** [comment]
+1 for links, I'd like to be consistent and besides that, such a big toggle looks strange near small text.

**Comment by batikanu** [comment]
@bryk @maciaszczykm  thanks for the feedbacks. Actually, the intend was to implement a new component for such fields and also password fields which shows by default "****" and displays the hidden value if you click on eye eye
  or switch 
switch.
 It was also stated by @bryk in the code as todo. I've just realized that such a component must include also label to have a better layout. It requires a bit more effort therefore I wanted to discuss it before implementing. 
I can change it to simple links or make it reusable component. What do you think?

**Comment by maciaszczykm** [comment]
@batikanu New reusable component sounds very nice :)

**Comment by rf232** [comment]
I personally think the usecases between more or less labels is quite different from showing/hiding secrets data. And for that something like the eye or switch actually feels quite natural. I just now looked at my password storage and it indeed uses such a eye icon.

minor nitpick: is your length in bytes correct for (non ascii) unicode strings?

**Comment by batikanu** [comment]
> minor nitpick: is your length in bytes correct for (non ascii) unicode strings?
I already receive the data as byte from the backend. Therefore I just use its length.

**Comment by bryk** [comment]
+1 on eye icon

**Comment by romlein** [comment]
If I'm understanding the use case correctly, I would use the eye pattern as shown in this interactive [InVision prototype](https://invis.io/6M91K6GQG#/198955708_Hidden) which references this Material spec for [icon toggles](https://material.google.com/components/buttons.html#buttons-toggle-buttons).
The problem with this solution is that the icon has to be a smaller than is ideal to fit in between the current spacing of rows, but I think this is a good start.
Toggles are typically for turning something _on_ or _off_.

**Comment by bryk** [comment]
All right, I see general agreement on the eye-icon approach. @batikanu Can you progress with this option? :)

**Comment by batikanu** [comment]
@bryk  I will proceed with eye-icon approach. @romlein why don't you prefer [eye-off icon ]( https://materialdesignicons.com/icon/eye-off ) when it is focused?

File: src/app/backend/resource/secret/secretdetail.go [hunk 3]
```diff
@@ -36,6 +36,8 @@ type SecretDetail struct {
 
 	// Used to facilitate programmatic handling of secret data.
 	Type api.SecretType `json:"type"`
+
```
Comment (bryk) [inline src/app/backend/resource/secret/secretdetail.go]: Please add small docs info here. About what this is.

File: src/app/frontend/secretdetail/detail.html [hunk 4]
```diff
@@ -15,14 +15,27 @@
...
-      <kd-info-card-entry ng-repeat="(key, value) in ::$ctrl.secretDetail.data"
-          title="{{::key}}">
-        <!-- TODO(#1059): Don't show plain text value. -->
-        <pre class="kd-pre-block">{{::$ctrl.formatDataValue(value)}}</pre>
-      </kd-info-card-entry>
-    </kd-info-card-section>
-  </kd-info-card>
+    <kd-secret-info secret="::$ctrl.secretDetail"></kd-secret-info>
+    <kd-info-card>
+        <kd-info-card-section name="{{::$ctrl.i18n.MSG_SECRET_INFO_DATA_SECTION}}">
```
Comment (bryk) [inline src/app/frontend/secretdetail/detail.html]: Please use the new i18n framework here :) It is much easier for you to write.

File: src/app/frontend/secretdetail/detail.html [hunk 5]
```diff
@@ -15,14 +15,27 @@
...
+            <kd-info-card-entry ng-repeat="(key, value) in ::$ctrl.secretDetail.data"
+                                title="{{::key}}">
+                <!-- TODO(#1059): Don't show plain text value. -->
```
Comment (bryk) [inline src/app/frontend/secretdetail/detail.html]: Is this TODO done?

File: src/app/frontend/secretdetail/togglehiddentext.scss [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+//
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+.kd-toggle-hidden-text-input {
+  border: 0 none;
+  font-size: 14px;
```
Comment (bryk) [inline src/app/frontend/secretdetail/togglehiddentext.scss]: Can you import the variables.scss file here and use variables from there?

**Comment by romlein** [comment]
@batikanu the eye on / off is potentially confusing for users, as there isn't good consistency around whether the icon shown should suggest [what will happen if clicked or be a label or what's currently shown](http://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan/1319#1319). Also, this is more closely aligned with the [Material spec for this UI element](https://material.google.com/components/buttons.html#buttons-toggle-buttons).

This is somewhat contingent on the use case though: how frequently will users be toggling visibility on and off, and what will the default be? If most users will choose to show all fields, I could see the more subtle eye-off icon as being less distracting and therefore more appropriate.

File: src/app/backend/resource/secret/secretdetail.go (hunk 3 above)
Comment (batikanu) [inline src/app/backend/resource/secret/secretdetail.go]: done.

File: src/app/frontend/secretdetail/detail.html (hunk 5 above)
Comment (batikanu) [inline src/app/frontend/secretdetail/detail.html]: done.

File: src/app/frontend/secretdetail/togglehiddentext.scss (hunk 6 above)
Comment (batikanu) [inline src/app/frontend/secretdetail/togglehiddentext.scss]: I've imported and used from them as much as I can use.

**Comment by batikanu** [comment]
Now it looks like this. PTAL
secret

File: src/app/frontend/common/components/togglehiddentext/togglehiddentext.html [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+
+    <!--<md-button  ng-show="!isActive" ng-click="isActive = !isAcitve" class="kd-toggle-eye-button-off md-icon-button md-mini" aria-label="Settings">-->
+        <!--<md-icon class="kd-toggle-eye-icon-off" md-font-set="material-icons"> remove_red_eye </md-icon>-->
+    <!--</md-button>-->
+
+
+    <!--<md-button ng-show="isActive" ng-click="isActive = isAcitve" class="kd-toggle-eye-button-on md-icon-button md-mini" aria-label="Settings">-->
+        <!--<md-icon class="kd-toggle-eye-icon-on" md-font-set="material-icons"> remove_red_eye </md-icon>-->
+    <!--</md-button>-->
+    <!--<i ng-show="isActive" ng-click="isActive = !isActive" class="material-icons kd-toggle-eye-icon-on">remove_red_eye</i>-->
```
Comment (rf232) [inline src/app/frontend/common/components/togglehiddentext/togglehiddentext.html]: I'm not a big fan of commented out code, can you clean this up?

File: i18n/messages-en.xtb [hunk 8]
```diff
@@ -813,16 +813,25 @@
   <translation id="5847167541694942228" key="MSG_PETSETDETAIL_PETSETINFO_9" desc="The message says that that many pods are pending (pet set details page).">{{ $ctrl.petSet.podInfo.pending}} pending</translation>
   <translation id="7332879554461510589" key="MSG_PETSETLIST_PETSETCARDLIST_0" desc="Column header \'Kind\' of a Pet Set List">Kind</translation>
   <translation id="2816069801101820166" key="MSG_PETSETLIST_PETSETCARDLIST_1" desc="Pet set list header: name.">Name</translation>
+  <translation id="3262303717958393654" key="MSG_PETSETLIST_PETSETCARDLIST_1" desc="Pet set list header: name.">Name</translation>
```
Comment (rf232) [inline i18n/messages-en.xtb]: Eek, lot of added duplications in this file. Not a problem with your code, but we might need to take a look at why this happens. Might be a problem in my i18n fix commit from PR #1386

File: src/app/frontend/common/components/togglehiddentext/togglehiddentext.html (hunk 7 above)
Comment (batikanu) [inline src/app/frontend/common/components/togglehiddentext/togglehiddentext.html]: done.

File: i18n/messages-en.xtb (hunk 8 above)
Comment (batikanu) [inline i18n/messages-en.xtb]: Strange. I cleaned duplication translations of this pull request.

**Comment by batikanu** [comment]
PTAL
