### PR TITLE
Make environment variables defined in envFrom shown in pod detail page

### LINKED ISSUE #2343: Environment variables defined using envFrom are not shown when viewing a pod's containers
##### Environment
```
Dashboard version: master
Kubernetes version: 1.7.2
Operating system: AWS/KOPS
```

##### Steps to reproduce
1. Create a deployment that uses `envFrom` to pull data from a ConfigMap, for example:
```
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: test
    labels:
      app: test
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: test
      spec:
        containers:
        - name: echoserver
          image: gcr.io/google_containers/echoserver:1.4
          envFrom:
          - configMapRef:
              name: my-config-map

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-config-map
  data:
    FOO: xxx
    BAR: yyy
```
2. View the pod in the Dashboard

##### Observed result
No environment variables are shown within the *Containers* card.

##### Expected result
I would have expected to see the environment variables listed, ideally with a link to the appropraite ConfigMap.

##### Comments
Environment variables specified explicitly using `env` are shown.

Furthermore, if `valueFrom`/`secretKeyRef` is used within `env` to reference a Secret value, then a link to the Secret is shown beside each such variable.

Looking at the JSON requested by the Dashboard from the API, I can see that no environment variables are returned:
```
   {
    "name": "echoserver",
    "image": "gcr.io/google_containers/echoserver:1.4",
    "env": [],
    "commands": null,
    "args": null
   }
```

If the API is simply not returning envFrom info, then this may well be an upstream issue.

### PR DESCRIPTION
**Pull request by zerda**
Fix #2343 

This commit create EnvVars from every item in referenced ConfigMap or Secret, then add them to the container info. 

The following is an example.

pod_detail

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: env-variables
spec:
  containers:
  - name: test
    image: gcr.io/google_containers/busybox
    command: [ "sh", "-c"]
    args:
    - while true; do
        echo -en '\n';
        printenv CONST_USER;
        printenv CONFIG_USER;
        printenv SECRET_USER;
        printenv TEST_FROM_CONFIG_USER;
        printenv TEST_FROM_CONFIG_TITLE;
        printenv FROM_SECRET_USER;
        printenv FROM_SECRET_TITLE;
        sleep 10;
      done;
    env:
    - name: CONST_USER
      value: alice
    - name: CONFIG_USER
      valueFrom:
        configMapKeyRef:
          name: config-env
          key: username
    - name: SECRET_USER
      valueFrom:
        secretKeyRef:
          name: secret-env
          key: username
    envFrom:
      - prefix: TEST_
        configMapRef:
          name: config-env-from
      - secretRef:
          name: secret-env-from
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-env
data:
  username: bob
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-env
data:
  username: Y2hhcmxpZQ==
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-env-from
data:
  FROM_CONFIG_USER: david
  FROM_CONFIG_TITLE: programmer
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-env-from
data:
  FROM_SECRET_USER: ZXZl
  FROM_SECRET_JOB: ZGVzaWduZXI=
```

### CODE REVIEW

File: src/app/backend/resource/pod/detail.go [hunk 1]
```diff
@@ -213,6 +213,57 @@ func extractContainerInfo(containerList []v1.Container, pod *v1.Pod, configMaps
 			}
 			vars = append(vars, variable)
 		}
+
+		for _, envFromVar := range container.EnvFrom {
```
Comment (floreks) [inline src/app/backend/resource/pod/detail.go]: Export this logic to separate function. Similar what we've done in `evalValueFrom`.

Comment (zerda) [reply src/app/backend/resource/pod/detail.go]: It's done, thank you for reviewing.

**Comment by floreks** [comment]
I'll take a look at this soon.

**Comment by floreks** [comment]
Tested and works ok. Thanks for contribution!

**Comment by leaflot** [comment]
Feb 01, 2020 - Kubernetes 1.17, this issue still alive and kicking
